### ISSUE TITLE
PANIC:  XX000: ERRORDATA_STACK_SIZE exceeded

### ISSUE THREAD

**Issue by sorccu** [sfackler/rust-postgres-macros#15]
The following snippet produces the error in the title. The snippet has already been reduced in size somewhat, but it seems like the error may be more related to total query length than anything else. However, I was unable to reproduce the error simply by copypasting a large amount of simple SELECTs, so I assume something else is going on as well.

It isn't possible to avoid the bug by using several functions instead of one large function, all active modules in the project seem to count against the limit.

```rust
#![feature(plugin)]
#![plugin(postgres_macros)]

fn main() {
    sql!("
        LOCK TABLE foo IN ACCESS EXCLUSIVE MODE
    ");

    sql!("
        ALTER TABLE foo
            ADD CONSTRAINT foo PRIMARY KEY (foo)
    ");

    sql!("
        ALTER TABLE foo
            ADD CONSTRAINT foo
                FOREIGN KEY (foo)
                REFERENCES foo (foo)
                ON DELETE RESTRICT
                ON UPDATE RESTRICT
    ");

    sql!("
        CREATE INDEX foo ON foo (foo)
    ");

    sql!("
        INSERT INTO foo VALUES ($1)
    ");

    sql!("
        LOCK TABLE foo IN ACCESS EXCLUSIVE MODE
    ");

    sql!("
        ALTER TABLE foo
            ADD CONSTRAINT foo PRIMARY KEY (foo)
    ");
}
```

Here's the full error you get on `cargo run`:

> PANIC:  XX000: ERRORDATA_STACK_SIZE exceeded
> LOCATION:  elog_start, elog.c:1320

I'm using the latest 64-bit nightly and postgres 9.4.5 on OS X 10.11.

**Comment by sorccu** [comment]
Awesome! Hoping for a quick v0.1.6 :)

**Comment by sfackler** [comment]
Just released :)
