### ISSUE TITLE
Interrupting build during download results in strange errors for subsequent builds

### ISSUE THREAD

**Issue by jwilm** [sfackler/rust-postgres-macros#25]
I interrupted a build during the postgresql source download (curl | tar) step. Since this created the postgresql folder, the rest of the Makefile assumed the source was properly downloaded during subsequent invocations. In my case, the build failed saying postgresql's 'configure' script wasn't found.

It would be nice to validate that the postgresql source folder is correct for follow up builds.

**Comment by sfackler** [comment]
Makes sense - an easy way to handle this would be to download/untar it to a temporary directory and then rename to the "real" one when that's one.

**Comment by jwilm** [comment]
Cool, I'll send a PR shortly
