### ISSUE TITLE
Building against latest nightly

### ISSUE THREAD

**Issue by bwbroersma** [sfackler/rust-postgres-macros#31]
* Moved InternedString->Symbol
* Dropped config argument

See PR https://github.com/sfackler/rust-postgres-macros/pull/30

**Comment by neoel** [comment]
Here's a travis build log when failing against latest nightly
https://travis-ci.org/wolbodo/rust-postgres-macros/builds/184872093

**Comment by sfackler** [comment]
Released 0.1.13

**Comment by bwbroersma** [comment]
Could you add a daily [Travis cron job](https://docs.travis-ci.com/user/cron-jobs/) to the [the settings](https://travis-ci.org/sfackler/rust-postgres-macros/settings) so the 'Build passing' is actually still valid for the latest nightly?

**Comment by sfackler** [comment]
Done! Didn't know that feature existed!
