### ISSUE TITLE
Error compiling because of curling of postgres and certificate issues

### ISSUE THREAD

**Issue by lancecarlson** [sfackler/rust-postgres-macros#32]
When I try to compile, it fails on some curl command to download this:

```
curl https://ftp.postgresql.org/pub/source/v9.4.4/postgresql-9.4.4.tar.gz | tar xzf - -C <path>
```

any idea what's up?

**Comment by sfackler** [comment]
The crate uses Postgres's query parser internally so it needs to download a copy of the source. Their certificate seems to be valid to me - do you have some TLS interception hardware in between you and the remote server?

**Comment by lancecarlson** [comment]
When I run curl manually it downloads fine. Not sure why it breaks during compile 

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sfackler** [comment]
Strange - it shouldn't be doing anything weird: https://github.com/sfackler/rust-postgres-macros/blob/master/Makefile#L37

**Comment by lancecarlson** [comment]
I removed this package as a dependency from my project. Will be hard to test now. :(

You can close!

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
