### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by maurer** [sfackler/rust-postgres-macros#4]
When trying to build with the postgres_macros plugin, I get the error:
rustc: symbol lookup error: /home/maurer/Sources/holmes-rust/server/target/deps/libpostgres_macros-30301e418b4506ad.so: undefined symbol: pvsnprintf

During chat in #rust, we thought that https://github.com/sfackler/rust-postgres-macros/blob/master/Makefile#L8-L15 was probably missing an object file from the newer revision of postgres.

**Comment by sfackler** [comment]
I'm not running into that failure locally, on an Arch Linux install, so I'm assuming it's being pulled in from some `#ifdef`'d code somewhere. Can you try adding `$(POSTGRES_DIR)/src/common/psprintf_srv.o` to the `POSTGRES_OBJS` variable in the Makefile: https://github.com/sfackler/rust-postgres-macros/blob/master/Makefile#L8-L15 and see if it builds for you then?
